### PR TITLE
Feature/repository archived tag

### LINKED ISSUE #111: Hide archived repositories
@pchorus Is it possible to hide archived repositories in the configuration? Otherwise, it would be helpful to see that the repository is archived.
I would prefer to not show archived repositories. :)

Thank you!

### PR DESCRIPTION
**Pull request by pchorus**
Add archived tag to archived repositories. Tag is shown in repositories list in configuration view, in actions dashboard and in commits dashboard.

Closes #111 

@marns93 What do you think?

config
actions-dashboard
commits-dashboard

### CODE REVIEW

**Review by marns93 — COMMENTED** [review]
@pchorus Thanks for adding this :)
I'm fine with a label. Cannot say much about the code changes itself, but what I can see from your pictures looks good.
So for my understanding: It isn't possible to click the deploy button for archived repositories if they are selected, correct?

**Comment by pchorus** [comment]
@marns93 No, at the moment, I just added the label to inform the user that the repository is archived, nothing else.
Maybe, it makes sense to disallow deploying archived repositories. Let's discuss this.

Is there anything else you want to forbid for archived repositories?

**Comment by pchorus** [comment]
Conclusion of our discussion:
Triggering a deployment should not be possible for archived repositories. When opening the deployment dialog for an archived repository, an appropriate message should be shown.

Furthermore, this information should be added to the readme file.

**Comment by marns93** [comment]
Thank you @pchorus ! :)

**Pull request merged**
